### ISSUE TITLE
Thread: Main Error: Deserializer is already assigned for "minecraft:moss_block" File: pmsrc/src/data/bedrock/block/convert/BlockStateToObjectDeserializer Line: 107 Type: InvalidArgumentException

### ISSUE THREAD

**Issue by liveguysytcoder** [pmmp/RegisterBlocksDemoPM5#8]
public function Bregister(): void {
        // Register blocks immediately
        $this->registerBlocks();

        // Add a worker start hook for async registration
        $this->getServer()->getAsyncPool()->addWorkerStartHook(function(int $worker) : void {
            $this->getServer()->getAsyncPool()->submitTaskToWorker(new class extends AsyncTask {
                public function onRun() : void {
                    Blockregisters::registerBlocks();
                }
            }, $worker);
        });
    }

    private static function registerBlocks(): void {
        self::registerMossBlock();
        self::registerEndPortal();
        self::registerEndGateWay();
    }

    private static function registerMossBlock(): void {
        self::registerBlock(BlockTypeNames::MOSS_BLOCK, ExtraVanillaBlocks::MOSS(), ["moss"]);
    }

    private static function registerEndPortal(): void {
        self::registerBlock(BlockTypeNames::END_PORTAL, ExtraVanillaBlocks::END_PORTAL(), ["endportal"]);
    }

    private static function registerEndGateWay(): void {
        self::registerBlock(BlockTypeNames::END_GATEWAY, ExtraVanillaBlocks::END_GATEWAY(), ["endgateway"]);
    }

    private static function registerBlock(string $id, Block $block, array $stringToItemParserNames): void {

        // Register the block with the runtime registry
        RuntimeBlockStateRegistry::getInstance()->register($block);

        // Map the block for deserialization and serialization
        GlobalBlockStateHandlers::getDeserializer()->mapSimple($id, fn() => clone $block);
        GlobalBlockStateHandlers::getSerializer()->mapSimple($block, $id);

        // Register the block names for item parsing
        foreach ($stringToItemParserNames as $name) {
            StringToItemParser::getInstance()->registerBlock($name, fn() => clone $block);
        }
    }
}
How do i even check if block is registered?

**Comment by GameParrot** [comment]
> public function Bregister(): void { // Register blocks immediately $this->registerBlocks();
> 
> ```
>     // Add a worker start hook for async registration
>     $this->getServer()->getAsyncPool()->addWorkerStartHook(function(int $worker) : void {
>         $this->getServer()->getAsyncPool()->submitTaskToWorker(new class extends AsyncTask {
>             public function onRun() : void {
>                 Blockregisters::registerBlocks();
>             }
>         }, $worker);
>     });
> }
> 
> private static function registerBlocks(): void {
>     self::registerMossBlock();
>     self::registerEndPortal();
>     self::registerEndGateWay();
> }
> 
> private static function registerMossBlock(): void {
>     self::registerBlock(BlockTypeNames::MOSS_BLOCK, ExtraVanillaBlocks::MOSS(), ["moss"]);
> }
> 
> private static function registerEndPortal(): void {
>     self::registerBlock(BlockTypeNames::END_PORTAL, ExtraVanillaBlocks::END_PORTAL(), ["endportal"]);
> }
> 
> private static function registerEndGateWay(): void {
>     self::registerBlock(BlockTypeNames::END_GATEWAY, ExtraVanillaBlocks::END_GATEWAY(), ["endgateway"]);
> }
> 
> private static function registerBlock(string $id, Block $block, array $stringToItemParserNames): void {
> 
>     // Register the block with the runtime registry
>     RuntimeBlockStateRegistry::getInstance()->register($block);
> 
>     // Map the block for deserialization and serialization
>     GlobalBlockStateHandlers::getDeserializer()->mapSimple($id, fn() => clone $block);
>     GlobalBlockStateHandlers::getSerializer()->mapSimple($block, $id);
> 
>     // Register the block names for item parsing
>     foreach ($stringToItemParserNames as $name) {
>         StringToItemParser::getInstance()->registerBlock($name, fn() => clone $block);
>     }
> }
> ```
> 
> } How do i even check if block is registered?

You are using the nethergames spoon right
